version: '3.3'

services:
  web_ui:
    container_name: web_ui
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/web_ui
    ports:
      - 3000:3000
    links:
      - app_server
    networks:
      - default

    command: npm run start
  
  app_server:
    container_name: app_server
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app

    ports:
      - 5000:5000
    networks:
      - default

    command:  uwsgi --http 0.0.0.0:5000 --master  --wsgi-file /app/app_server.py --ini /app/app_server.ini --http-to /pids/app_server.sock
    environment:
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - PYTHONPATH=/app
networks:
  default:
    external: false
