version: '3.3'

services:
  web_ui:
    container_name: web_ui
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/web_ui/src
      - ./frontend/public:/web_ui/public
    ports:
      - 3000:3000
    links:
      - app_server
    networks:
      - default

    command: npm run start
  
  app_server:
    container_name: app_server
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app

    ports:
      - 5000:5000
    networks:
      - default

    command:  pipenv run gunicorn --worker-class eventlet -w 1  -b app_server:5000 'app_server:create_app()' 
    environment:
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - PYTHONPATH=/app
networks:
  default:
    external: false
